### ISSUE TITLE
is sharing link wrong ?

### ISSUE THREAD

**Issue by bourgeoa** [solidcryptpad/solidcryptpad#3]
the link fails with a 404
```
https://solidcryptpad.github.io/share?file=https%3A%2F%2Fbourgeoa.solidcommunity.net%2Fsolidcryptpad%2Ftest.md&key=YjRjYTFkNDM4MTA2ZGY5YmQ0YjU0YmVkYzAyNGYzMmU4MTdhMTU2NGM0OWI1MTIwMGVkZjZmOTM2OTczZTYwYg%3D%3D&group=https%3A%2F%2Fbourgeoa.solidcommunity.net%2Fsolidcryptpad-data%2Fgroups%2Fgroup-2f297015b432b85708c2e1cd822956ebd69bea0c60f399b6c68f1ac948c86663.ttl%23some-group-name
```

it seems that 
`https://solidcryptpad.github.io/` should be `https://solidcryptpad.github.io/solidcryptpad/`

**Comment by Otto-AA** [comment]
Thanks for pointing this out! It should be fixed by https://github.com/solidcryptpad/solidcryptpad/commit/47b699c1d0b8768c12f38f33a8e75c27158af08a

If it doesn't work, please let us know. My internet is currently too slow to test it :/

The origin of the error is, that while developing we didn't have a `/solidcryptpad/` path but expected everything to start from `/`, so we missed this while moving it to github pages.

**Comment by bourgeoa** [comment]
Thanks seems to be solved.
